# script to check if the A1/A2 alleles in the genetic data for the 3 datasets are in the proper order
# compared to the effect/reference alleles in the reference files with the expression weights

# this script needs to be run with the 3.3.2 version of the root R installation: /share/apps/R-3.3.2/bin/R
# empty working environment

rm(list = ls())

# load necessary libraries

library(RSQLite)
library(data.table)
library(NMF)

# variables

datasets <- c("PEIC", "Harvard", "Yale")

# read in the BIM files of the PLINK binary-fileset used for the TWAS in each case

# PEIC

peic_bim <- as.data.frame(fread("./check_allele_order/pe.dbSNP.150.matched.mmn.subset.bim", header = F, sep = "\t"))

# Mei

mei_bim <- as.data.frame(fread("./check_allele_order/mclean_fgh19.typed.and.imputed.dbSNP.150.matched.bim", header = F, sep = "\t"))

# Elliot

elliot_bim <- as.data.frame(fread("./check_allele_order/MPRC_Hong.typed.and.imputed.clean.dbSNP.150.matched.bim", header = F, sep = "\t"))
                          
# put all three BIM files in a list
                            
bim_list <- list(peic_bim, mei_bim, elliot_bim)

# get the names of the .db files that contain the expression weights for all 9 tissues

# the ones downloaded from PredictDB (expression weights generated by the PrediXcan team from GTEx data)

predb_files <- paste("./PredictDB/", list.files(path = "./PredictDB", pattern = ".db", recursive = TRUE), sep = "")

# the one that Laura sent us with expression weights for DLPFC generated from Common Mind Consortium data

cmc_file <- "./common_mind/CommonMindDB.v2/DLPFC_newMetax.db"

# put them all together in an only vector

db_files <- c(predb_files, cmc_file)

sqlite.driver <- dbDriver("SQLite")

# in a loop, open connection to database file, extract the reference/effect allele info and compare to the
# A1/A2 alleles of the BIM files

# create matrices in which to store fractions of SNPs in the same direction, on one hand, and on the
# opposite direction, on the other one

same_mat <- matrix(nrow = length(db_files), ncol = length(datasets))
opp_mat <- matrix(nrow = length(db_files), ncol = length(datasets))


for(i in 1:length(db_files)){
  
  # open the connection to the .db file
  
  db_conn <- dbConnect(sqlite.driver,  dbname = db_files[i])
  
  # extract table that contains expression weight data
  
  expr_wgts <- dbReadTable(db_conn, "weights")
  
  # create a column that contains effect_allele:reference_allele
  
  expr_wgts$eff_ref <- paste(expr_wgts$eff_allele, expr_wgts$ref_allele, sep = ":")
  
  # and another one with the opposite
  
  expr_wgts$ref_eff <- paste(expr_wgts$ref_allele, expr_wgts$eff_allele, sep = ":")
  
  # in a loop, get BIM file
  
  for(j in 1:length(datasets)){
    
    # extract BIM file from list
    
    bim <- bim_list[[j]]
    
    # create a column that contains A1:A2 (it should match the eff_ref columns of the expression weights table)

    bim$A1_A2 <- paste(bim$V5, bim$V6, sep = ":")
    
    # merge both tables using the "rsID"
    
    wgts_bim <- merge(expr_wgts[,c("rsid", "eff_ref", "ref_eff")], bim[,c("V2", "A1_A2")], by.x = "rsid", by.y = "V2")
    
    # check for how many alleles, the A1_A2 column matches the "eff_ref" column
   
    match_count <- length(which(wgts_bim$A1_A2 == wgts_bim$eff_ref)) 
    
    # and now for how many alleles, it matches the "ref_eff" column
    
    mismatch_count <- length(which(wgts_bim$A1_A2 == wgts_bim$ref_eff))
    
    # get the fractions and store them in the proper position in corresponding matrix
    
    same_mat[i,j] <- match_count/nrow(wgts_bim)
    opp_mat[i,j] <- mismatch_count/nrow(wgts_bim) 
  }
  
  # cut connection to db file before establishing a new one in the next iteration
  
  dbDisconnect(db_conn)
  
  # print out iteration of the main loop
  
  print(paste(i, "out of", length(db_files), "tables checked"))
  
}

# add the tissue-names and dataset names as row names and column names, respectively

colnames(same_mat) <- datasets
colnames(opp_mat) <- datasets

# extract tissue names from .db file names

tissue_names <- gsub("gtex_v7_", "", gsub(".*/", "", gsub("_newMetax.db", "", gsub("_imputed.*", "", db_files))))

rownames(same_mat) <- tissue_names
rownames(opp_mat) <- tissue_names

# export result tables as heatmaps

# open pdf file
 
pdf("./check_allele_order/allele_match_mismatch_fractions_2.pdf", onefile = F, width = 18)

# set visual parameters so both heatmaps appear on the same page side-by-side

par(mfrow=c(1,2))

# generate heatmaps

aheatmap(same_mat, txt = round(same_mat, digits = 3), main = "Alleles  match (fraction)")
aheatmap(opp_mat, txt = round(opp_mat, digits = 3), main = "Alleles flipped (fraction)")

dev.off()


# save objects in working environment into an .RData object

save.image("./check_allele_order/check_allele_order.RData")
